import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConnectDB } from "./lib/db";
import { NextUIProvider } from "@nextui-org/react";

import "./globals.css";
import NavbarComponent from "./components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  ConnectDB();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <NavbarComponent />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
